spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Nestify?useUnicode=yes&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30_000
      connection-timeout: 5_000
      poolName: "hikari-cp"
  jooq:
    sql-dialect: MYSQL